"""

This is a very simple script that points to a Windows directory and takes a username. 
I may implement an autogenerated rudimentary password system...
but I didn't want a  user inputted password system as it's not secure- 
even though this is just for my own testing I'd still rather not 
breach that particular area of security practices. 

As simple as it is, it's already had multiple iterations due to design flaws. 
            I would definitely consider it a work in progress.

"""

import time

def welcome():
    print ("Welcome to a basic Python login screen!")
    welcomemenu = str(input("Type \"Login\", \"Register\", or \"Close\" \n")).lower() 
    if welcomemenu == "login":
        print ("Welcome to the login screen")
        login()
    elif welcomemenu == "register":
        print ("Welcome to the register screen")
        register()
    elif welcomemenu == "close":
        quit()
    elif welcomemenu == "secret":
        print ("You've reached the secret menu! For now start over... \nThis may have something neat later on!")
    if welcomemenu not in ["login", "register", "close", "secret"]:
        print("This is not recognized please try again")
        welcome()

def register():
   file1 = open("C:/test/User_Dat.txt", "r+")
   global username
   username = str(input("Please enter a username \n")).lower()
   readfile = file1.read()
   if username in readfile: 
        print('\n\n---------------------------------------') 
        print('The user', username, 'has already been created.')
        print('---------------------------------------\n\n') 
        welcome()
   else: 
        print('\n\n---------------------------------------') 
        print('The user', username, 'has been created!')  
        print('---------------------------------------\n\n') 
        file1.write(username)
        file1.write("\n")
        file1.close()
        login()
    
def login():
   file1 = open("C:/test/User_Dat.txt", "r")
   global username
   username = str(input("Please enter a username \n")).lower()
   readfile = file1.read()
   if username in readfile: 
        print('\n\n---------------------------------------') 
        print("Correct credentials!")
        print("You are now logged in!")
        print('---------------------------------------\n\n') 
        startgame()
   else:
        print('\n\n---------------------------------------')
        print("Incorrect credentials.")
        print('---------------------------------------\n\n') 
        time.sleep(2)
        welcome()

def startgame():
    print("Loading [--        ]")
    time.sleep(1)
    print("Loading [-----     ]")
    time.sleep(1)
    print("Loading [--------  ]")
    time.sleep(1)
    print("Loading [----------]")
    time.sleep(1)
    print('\n\n---------------------------------------')
    print("Welcome back",username+"!")
    print('---------------------------------------\n\n') 
    input("Press Enter to continue...")
    
welcome()
