import time
import os

"""

This is a very simple script that points to a Windows directory and takes a username. 
I may implement an autogenerated rudimentary password system...
but I didn't want a  user inputted password system as it's not secure- 
even though this is just for my own testing I'd still rather not 
breach that particular area of security practices. 

"""

def welcome():
    print ("Welcome to a basic Python login screen!")
    welcomemenu = str(input("Type \"Login\", \"Register\", or \"Close\" \n")).lower() 
    if welcomemenu == "login":
        print ("Welcome to the login screen")
        login()
    elif welcomemenu == "register":
        print ("Welcome to the register screen")
        register()
    elif welcomemenu == "close":
        quit()
    elif welcomemenu == "secret":
        print ("You've reached the secret menu! For now start over... \nThis may have something neat later on!")
    if welcomemenu not in ["login", "register", "close", "secret"]:
        print("This is not recognized please try again")
        welcome()

def register():
    username =  str(input("***CASE SENSITIVE***\nPlease enter a username \n")).lower() #It's not actually case sensitive lol
    file = open("C:/test/User_Dat.txt","a")
    for line in open("C:/test/User_Dat.txt","r").readlines(): # Read the lines
        login_info = line.split() # Split on the space, and store the results in a list of two strings
        if username == login_info[0]:
            print("There is already a user with this name please try again.")
            register()
    file.write(username)
    file.write(" ")
    file.write("\n")
    file.close()
    login()

def login():
    global username
    username = input("***CASE SENSITIVE***\nPlease enter your username  \n").lower() 
    for line in open("C:/test/User_Dat.txt","r").readlines(): # Read the lines
        login_info = line.split() # Split on the space, and store the results in a list of two strings
        if username == login_info[0]:
            print("Correct credentials!")
            print("You are now logged in!")
            startgame()
            return True
        else:
            print("Incorrect credentials.")
            time.sleep(2)
            welcome()
            return False

def startgame():
    print("Loading [--        ]")
    time.sleep(1)
    print("Loading [-----     ]")
    time.sleep(1)
    print("Loading [--------  ]")
    time.sleep(1)
    print("Loading [----------]")
    time.sleep(1)
    print("Welcome back",username+"!")
    input("Press Enter to continue...")
    
welcome()
